services:
  mongo:
    image: mongo:latest
    container_name: bookreview-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bookreview

  backend:
    build: ./backend
    container_name: bookreview-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookreviewdb
    depends_on:
      - mongo
    networks:
      - bookreview

  frontend:
    build: ./frontend
    container_name: bookreview-frontend
    ports:
      - "8080:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - bookreview

volumes:
  mongo_data:

networks:
  bookreview:
    driver: bridge
