name: Docker Build and Push to GHCR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image to GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/bookreview-backend:latest ./backend
          docker push ghcr.io/${{ github.repository_owner }}/bookreview-backend:latest

      - name: Build and push frontend image to GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/bookreview-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/bookreview-frontend:latest
